//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by CSQLAFX.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDI_ICON2                       102
#define IDI_ICON1                       103
#define IDM_EX1                         32768
#define IDM_EX2                         32769
#define IDM_EX3                         32770
#define IDM_EX4                         32771
#define IDM_EX5                         32772
#define IDM_EX6                         32773
#define ID_TEST                         32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
